### PR TITLE
New data structure

### PR DESCRIPTION
**Pull request by cclark1e**

### CODE REVIEW

**Comment by chofski** [comment]
What precisely has changed in the data structure? I struggle to see any major differences.

**Comment by cclark1e** [comment]
Apologies, when we had a chat about this last month I took new data structure to mean a new object representing constructs containing the pre-existing objects for glyphs and interactions. 

I added the `construct` class that now contains these objects in attributes so that changes can be stored in the construct before it is rendered, as opposed to passing all information to `render_part_list`.

Did you want changes to how glyphs are directly represented, rather than the overarching structure?

**Comment by chofski** [comment]
No I think the structure is OK, but there are a couple tweaks needed to best capture things. For example a class should be capitalised (i.e. Construct not construct) and for the interactions a reference to the dictionary defining it should be used. Not a numeric value as the position to the part could change. I may merge this is and then edit directly as the master branch is not us direct use yet.

**Comment by cclark1e** [comment]
I can't think of a great way to remove the numeric indexes and still be able to specifically refer to glyphs in the construct - referring to the glyph dictionary for defining interaction positions will lead to ambiguity if there is multiple of the same glyph type in the same construct.

**Comment by chofski** [comment]
Dictionaries are passed by reference so you can use them like that and if it moves index the reference stays the same. I'll code an example to show you.

**Comment by cclark1e** [comment]
Hi Tom, would it be possible to get an update on this? I've given it a few more attempts but can't seem to get it working as you described.

**Comment by chofski** [comment]
Sorry for not getting back to you. Maybe the following clarifies it, where parts and links correspond to the sequence of parts and the connections between them:
```
parts = [ {'name': 'A'}, {'name': 'B'}, {'name': 'C'}]
links = [(parts[0], parts[2])]
```
In this example, the links are not to indexes in the parts list, but are references to the actual dictionary objects. So, if a new parts list is created, the links are still to the correct for that list too:
```
new_parts = [parts[2], parts[0], parts[1]]
```
Does that help?

**Comment by cclark1e** [comment]
Thank you, I've got it working. I spent ages trying to work on some overly complex solution until I realised all I needed was the `is` operator.

**Pull request merged**
